# Generated by Django 4.0.5 on 2022-06-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
    ]
