# Generated by Django 4.0.5 on 2022-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_home_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
